### ISSUE TITLE
bug: crash after upgrading to new version

### ISSUE THREAD

**Issue by tyrossel** [tehcyx/terraform-provider-kind#35]
Hello, thank you for maintaining this project ! After upgrading it, I go the following issue: 

```shell
╷
│ Error: Request cancelled
│
│   with module.kind.kind_cluster.cluster,
│   on .terraform/modules/kind/main.tf line 1, in resource "kind_cluster" "cluster":
│    1: resource "kind_cluster" "cluster" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-kind plugin:

panic: interface conversion: interface {} is map[string]interface {}, not map[string]string

goroutine 46 [running]:
github.com/tehcyx/terraform-provider-kind/kind.flattenKindConfig(0xc00056ae30?)
        github.com/tehcyx/terraform-provider-kind/kind/structure_kind_config.go:45 +0x5bf
github.com/tehcyx/terraform-provider-kind/kind.resourceKindClusterCreate(0x0?, {0x0, 0x0})
        github.com/tehcyx/terraform-provider-kind/kind/resource_cluster.go:120 +0x2e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x109d6d0?, {0x109d6d0?, 0xc0002a6c60?}, 0xd?, {0x0?, 0x0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0006841c0, {0x109d6d0, 0xc0002a6c60}, 0xc00025fa00, 0xc0002fcf00, {0x0, 0x0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000700000, {0x109d6d0?, 0xc0002a6b40?}, 0xc0002e4370)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003e8000, {0x109d6d0?, 0xc0002a6150?}, 0xc0002261c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xecf5e0?, 0xc0003e8000}, {0x109d6d0, 0xc0002a6150}, 0xc000226070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002501e0, {0x10a1c60, 0xc000102340}, 0xc0003ee120, 0xc0004901b0, 0x16d2720, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0002501e0, {0x10a1c60, 0xc000102340}, 0xc0003ee120, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-kind plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
For the timebeing, I rolled back to version 0.0.17. 
Here is the terraform code I use: 
```hcl
variable "cluster_name" {
  description = "The name to give to the cluster."
  type        = string
  default     = "kind"
}

variable "kubernetes_version" {
  description = "Kubernetes version to use for the KinD cluster (images available https://hub.docker.com/r/kindest/node/tags[here])."
  type        = string
  default     = "v1.26.0"
}

variable "nodes" {
  description = "List of nodes"
  type        = list(map(string))
  default = [
    {
      "platform" = "my-platform"
    },
    {
      "platform" = "my-platform"
    },
    {
      "platform" = "my-platform"
    }
  ]
}

resource "kind_cluster" "cluster" {
  name = var.cluster_name

  node_image = "kindest/node:${var.kubernetes_version}"

  kind_config {
    kind        = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
      role = "control-plane"
    }

    dynamic "node" {
      for_each = var.nodes
      content {
        role   = "worker"
        labels = node.value
      }
    }
  }
}

```
Let me know if you need more information on my side ;)

**Comment by tehcyx** [comment]
Found the culprit, as well as some other issues that are hopefully all fixed now.
The tests on the repo unfortunately were reporting results for the `master` branch instead of the PR, that is fixed now. As well as the issues that were happening when creating clusters.

A new release was just cut, which also includes the update to kind [v0.0.19](https://github.com/tehcyx/terraform-provider-kind/releases/tag/v0.0.19)

Closing this issue. Please re-open or create a new issue if you find the fix to not be working.

**Comment by tyrossel** [comment]
Thank you for your prompt reactivity. I just tested version 0.1.0, it works perfectly. Have a nice day

**Comment by tehcyx** [comment]
Thanks for reporting back.
